package org.reeky.natutils.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0062A1)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD0E4FF)
val onPrimaryContainerLight = Color(0xFF001D35)
val secondaryLight = Color(0xFF525F70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6E4F7)
val onSecondaryContainerLight = Color(0xFF0F1D2A)
val tertiaryLight = Color(0xFF6A5779)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF1DAFF)
val onTertiaryContainerLight = Color(0xFF241432)
val errorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorLight = Color(0xFFFFFFFF)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDFCFF)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFDFCFF)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFDFE3EB)
val onSurfaceVariantLight = Color(0xFF42474E)
val outlineLight = Color(0xFF73777F)
val inverseOnSurfaceLight = Color(0xFFF1F0F4)
val inverseSurfaceLight = Color(0xFF2F3033)
val inversePrimaryLight = Color(0xFF9CCAFF)
@Suppress("unused")
val shadowLight = Color(0xFF000000)
val surfaceTintLight = Color(0xFF0062A1)
val outlineVariantLight = Color(0xFFC2C7CF)
val scrimLight = Color(0xFF000000)

val primaryDark = Color(0xFF9CCAFF)
val onPrimaryDark = Color(0xFF003257)
val primaryContainerDark = Color(0xFF00497B)
val onPrimaryContainerDark = Color(0xFFD0E4FF)
val secondaryDark = Color(0xFFBAC8DB)
val onSecondaryDark = Color(0xFF243140)
val secondaryContainerDark = Color(0xFF3B4857)
val onSecondaryContainerDark = Color(0xFFD6E4F7)
val tertiaryDark = Color(0xFFD5BEE5)
val onTertiaryDark = Color(0xFF3A2948)
val tertiaryContainerDark = Color(0xFF514060)
val onTertiaryContainerDark = Color(0xFFF1DAFF)
val errorDark = Color(0xFFFFB4AB)
val errorContainerDark = Color(0xFF93000A)
val onErrorDark = Color(0xFF690005)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1C1E)
val onBackgroundDark = Color(0xFFE2E2E6)
val surfaceDark = Color(0xFF1A1C1E)
val onSurfaceDark = Color(0xFFE2E2E6)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFC2C7CF)
val outlineDark = Color(0xFF8C9199)
val inverseOnSurfaceDark = Color(0xFF1A1C1E)
val inverseSurfaceDark = Color(0xFFE2E2E6)
val inversePrimaryDark = Color(0xFF0062A1)
@Suppress("unused")
val shadowDark = Color(0xFF000000)
val surfaceTintDark = Color(0xFF9CCAFF)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
